services:
  db:
    image: 'postgres:latest'
    container_name: document_postgres
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    env_file:
      - ../document-management-service/.env
    volumes:
      - "local_pgdata:/var/lib/postgresql/data"
    ports:
      - '5436:5432'
    #    networks:
    #      - postgres
    restart: always
#networks:
#  postgres:
#    driver: bridge
volumes:
  local_pgdata:
