spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
        url: jdbc:postgresql://${POSTGRES_DEV_HOST}:${POSTGRES_DEV_PORT}/${DM_SERVICE_DEV_DB}
        username: ${POSTGRES_DEV_USER}
        password: ${POSTGRES_DEV_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    servlet:
        multipart:
            enabled: true
    main:
        allow-bean-definition-overriding: true

server:
    port: 8085
    servlet:
        context-path: /dss/api/v1/
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_DEV_HOST}:${EUREKA_DEV_PORT}/eureka/


springdoc:
    swagger-ui:
        tags-sorter: alpha
        display-operation-id: false
        operations-sorter: alpha
        display-request-duration: true

# JWT Properties expiration and refresh times (in milliseconds)
# Secret key
jwt:
    secret:
        key: 8KvVu4Bn2KwBNX1MdnXY6VaRVLekVxurk3aaJxnzdCuZL6AHEL0EnnAOYLZtHWUr
    access:
        token:
            expiration: 1800000 # 30 min in milliseconds for token expiration time
    refresh:
        token:
            expiration: 604800000    # 7 days in milliseconds
logging:
    level:
        org:
            hibernate:
                sql: DEBUG
                type: TRACE
                type.descriptor.sql: TRACE

file:
    storage:
        upload:
            location: ${FILE_STORAGE_LOCATION:/app/storage} #Make the storage path configurable using environment variables,
        max-size: 10MB
        document:
            supportedFileTypes:
                - pdf
                - docx
                - jpg
                - png
                - image/jpeg
                - pdf
