create-test-data: false
datasource:
    name: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    port: ${DB_PORT}
    url: ${DB_URL}
spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true

#pgadmin:
#    email: ${PGADMIN_EMAIL}
#    password: ${PGADMIN_PASSWORD}
